### ISSUE TITLE
Expectation of N7 in equation (1)

### ISSUE THREAD

**Issue by martinmamql** [Philip-Bachman/amdim-public#12]
Dear AMDIM authors,

Greetings!

When I am working with the code base, it seems that we take log-sum-exp of all negative samples and positive samples here:
https://github.com/Philip-Bachman/amdim-public/blob/master/costs.py#L92

This, according to my understanding, refers to
![Screenshot from 2020-02-24 11-39-59](https://user-images.githubusercontent.com/29204081/75171983-85832a80-56fa-11ea-9a40-bc7f3325d2c1.png)

Then the following line, we calculate the mean of the score matrices
https://github.com/Philip-Bachman/amdim-public/blob/master/costs.py#L103

This I believe refers to 
![Screenshot from 2020-02-24 11-42-08](https://user-images.githubusercontent.com/29204081/75172094-b6635f80-56fa-11ea-9291-1a1e7b3f6f6b.png)

My question is, where was the E_{N7}
![Screenshot from 2020-02-24 11-42-52](https://user-images.githubusercontent.com/29204081/75172193-dd219600-56fa-11ea-954e-640347d65668.png)
of the objective
![Screenshot from 2020-02-24 11-43-09](https://user-images.githubusercontent.com/29204081/75172317-10642500-56fb-11ea-93d9-9295c7848bfd.png)

implemented in the code?

Thank you so much!

Sincerely,
Martin

**Comment by Philip-Bachman** [comment]
The expectation is approximated via the minibatch sampling. I.e., other images in the batch are IID wrt the current image and the union of their features (which we sum over as you mentioend) are IIDish samples from the space of possible negative samples. I say "IIDish" because we get "clumps" of correlated mid-level features from each other image, which is still formally correct but reduces the effective sample size a bit.

**Comment by martinmamql** [comment]
Thank you very much! It is truly appreciated!
